function esc(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function normalizeUserBlockLines(blockText) {
  const lines = String(blockText || '').replace(/\r/g, '').split('\n');
  const deindented = lines.map((line) => line.replace(/^ {8}/, ''));
  while (deindented.length && deindented[0].trim() === '') deindented.shift();
  while (deindented.length && deindented[deindented.length - 1].trim() === '') deindented.pop();
  return deindented;
}

function collectEnabledHandlers(widgets) {
  const handlers = [];
  for (const w of widgets) {
    const events = w.events || {};
    for (const [evt, enabled] of Object.entries(events)) {
      if (!enabled) continue;
      const method = `on_${w.name}_${evt}`;
      const args = evt === 'change' && w.type === 'Scale' ? 'self, value'
        : evt === 'key' ? 'self, event'
        : 'self';
      handlers.push({ widget: w, event: evt, method, args });
    }
  }
  return handlers;
}

function extractMarkedUserBlocks(code) {
  const blocks = {};
  const re = /# >>> USER CODE START: ([A-Za-z0-9_]+)\n([\s\S]*?)\n\s*# <<< USER CODE END: \1/g;
  let m;
  while ((m = re.exec(String(code || ''))) !== null) {
    blocks[m[1]] = normalizeUserBlockLines(m[2]).join('\n');
  }
  return blocks;
}

function extractLegacyMethodBodies(code) {
  const blocks = {};
  const lines = String(code || '').replace(/\r/g, '').split('\n');
  const generatedHandlersBanner = /^\s{4}#\s*─+\s*Event Handlers/;
  const generatedHandlersBannerNoIndent = /^#\s*─+\s*Event Handlers/;

  for (let i = 0; i < lines.length; i++) {
    const defMatch = lines[i].match(/^\s{4}def\s+([A-Za-z0-9_]+)\([^)]*\):\s*$/);
    if (!defMatch) continue;

    const methodName = defMatch[1];
    const body = [];
    let j = i + 1;
    while (j < lines.length) {
      if (/^\s{4}def\s+/.test(lines[j]) || /^run\(App\)\s*$/.test(lines[j]) || generatedHandlersBanner.test(lines[j])) break;
      body.push(lines[j]);
      j += 1;
    }
    i = j - 1;

    const normalized = normalizeUserBlockLines(body.join('\n'));
    const cleaned = normalized.filter((line) => !generatedHandlersBannerNoIndent.test(line));
    if (cleaned.length) {
      blocks[methodName] = cleaned.join('\n');
    }
  }

  return blocks;
}

function addUserBlockLines(L, key, userBlocks, hintComment) {
  const body = normalizeUserBlockLines(userBlocks[key] || '');
  if (body.length === 0) {
    if (hintComment) L.push(`        ${hintComment}`);
    L.push('        pass');
  } else {
    body.forEach((line) => L.push(`        ${line}`));
  }
}

// ══════════════════════════════════════════════════════════
//  gui.py — AUTO-GENERATED (includes boilerplate + runner)
// ══════════════════════════════════════════════════════════
export function generateGuiPy(widgets, windowTitle, canvasSize, windowResizable, windowBg) {
  const L = [];
  const hasPygame = widgets.some((w) => w.type === 'PygameCanvas');

  L.push('# ──────────────────────────────────────────────');
  L.push('# gui.py — AUTO-GENERATED by Pythonizer');
  L.push('# Do not edit this file. Use main.py instead.');
  L.push('# ──────────────────────────────────────────────');
  L.push('import tkinter as tk');
  L.push('from tkinter import messagebox');
  if (hasPygame) {
    L.push('import sys');
    L.push('import os');
  }
  L.push('');
  L.push('');
  L.push('class AppGUI:');
  L.push('    """Base GUI class. All widgets are created here."""');
  L.push('');
  L.push('    def __init__(self, root):');
  L.push('        self.root = root');
  L.push(`        self.root.title("${esc(windowTitle)}")`);
  L.push(`        self.root.geometry("${canvasSize.width}x${canvasSize.height}")`);
  L.push(`        self.root.resizable(${windowResizable ? 'True, True' : 'False, False'})`);
  L.push(`        self.root.configure(bg="${windowBg || '#ffffff'}")`);
  L.push('');
  L.push('        self._create_widgets()');
  L.push('        self._bind_events()');
  L.push('        self._expose_widgets()');
  L.push('        self.on_start()');
  L.push('');
  L.push('    def _create_widgets(self):');

  if (widgets.length === 0) {
    L.push('        pass');
  } else {
    const radioGroups = new Set();

    for (const w of widgets) {
      L.push('');
      const dis = w.props.enabled === false ? ', state="disabled"' : '';
      const widgetBg = w.props.bg || '#ffffff';
      const widgetFg = w.props.fg || '#000000';

      switch (w.type) {
        case 'Button':
          L.push(`        self.${w.name} = tk.Button(self.root, text="${esc(w.props.text)}"${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}", activebackground="${widgetBg}", activeforeground="${widgetFg}")`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;

        case 'Label':
          L.push(`        self.${w.name} = tk.Label(self.root, text="${esc(w.props.text)}"${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}")`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;

        case 'Entry':
          L.push(`        self.${w.name} = tk.Entry(self.root${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}", insertbackground="${widgetFg}")`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;

        case 'Text':
          L.push(`        self.${w.name} = tk.Text(self.root${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}", insertbackground="${widgetFg}")`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;

        case 'Listbox':
          L.push(`        self.${w.name} = tk.Listbox(self.root${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}")`);
          if (w.props.items) {
            w.props.items.split(',').map((s) => s.trim()).forEach((item, i) => {
              L.push(`        self.${w.name}.insert(${i}, "${esc(item)}")`);
            });
          }
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;

        case 'Checkbutton':
          L.push(`        self.${w.name}_var = tk.BooleanVar()`);
          L.push(`        self.${w.name} = tk.Checkbutton(self.root, text="${esc(w.props.text)}", variable=self.${w.name}_var${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}", activebackground="${widgetBg}", activeforeground="${widgetFg}", selectcolor="#ffffff")`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;

        case 'Radiobutton': {
          const grp = w.props.group || 'group1';
          if (!radioGroups.has(grp)) {
            radioGroups.add(grp);
            L.push(`        self.${grp}_var = tk.StringVar(value="")`);
          }
          L.push(`        self.${w.name} = tk.Radiobutton(self.root, text="${esc(w.props.text)}", variable=self.${grp}_var, value="${esc(w.props.value)}"${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}", activebackground="${widgetBg}", activeforeground="${widgetFg}", selectcolor="#ffffff")`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;
        }

        case 'Scale': {
          const tickInt = parseInt(w.props.tickinterval) || 0;
          const resolution = parseFloat(w.props.resolution) || 1;
          const showVal = w.props.showvalue !== false;
          let scaleOpts = `from_=${w.props.from_}, to=${w.props.to}, orient=tk.${(w.props.orient || 'horizontal').toUpperCase()}`;
          if (tickInt > 0) scaleOpts += `, tickinterval=${tickInt}`;
          if (resolution !== 1) scaleOpts += `, resolution=${resolution}`;
          if (!showVal) scaleOpts += ', showvalue=False';
          L.push(`        self.${w.name} = tk.Scale(self.root, ${scaleOpts}${dis})`);
          L.push(`        self.${w.name}.config(bg="${widgetBg}", fg="${widgetFg}", troughcolor="#e0e0e0", highlightthickness=0)`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;
        }

        case 'PygameCanvas':
          L.push(`        self.${w.name} = tk.Frame(self.root, bg="${w.props.bg || '#1e1e2e'}", bd=0, highlightthickness=0)`);
          L.push(`        self.${w.name}.place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`);
          break;
      }
    }
  }

  // ── _bind_events ──
  L.push('');
  L.push('    def _bind_events(self):');
  const bindings = [];
  for (const w of widgets) {
    const events = w.events || {};
    for (const [evt, enabled] of Object.entries(events)) {
      if (!enabled) continue;
      switch (evt) {
        case 'click':
          bindings.push(`        self.${w.name}.config(command=self.on_${w.name}_click)`);
          break;
        case 'change':
          if (w.type === 'Scale') {
            bindings.push(`        self.${w.name}.config(command=self.on_${w.name}_change)`);
          } else if (w.type === 'Checkbutton' || w.type === 'Radiobutton') {
            bindings.push(`        self.${w.name}.config(command=self.on_${w.name}_change)`);
          } else if (w.type === 'Entry') {
            bindings.push(`        self.${w.name}.bind("<KeyRelease>", lambda e: self.on_${w.name}_change())`);
          } else if (w.type === 'Text') {
            bindings.push(`        self.${w.name}.bind("<KeyRelease>", lambda e: self.on_${w.name}_change())`);
          }
          break;
        case 'select':
          bindings.push(`        self.${w.name}.bind("<<ListboxSelect>>", lambda e: self.on_${w.name}_select())`);
          break;
        case 'focus':
          bindings.push(`        self.${w.name}.bind("<FocusIn>", lambda e: self.on_${w.name}_focus())`);
          break;
        case 'key':
          bindings.push(`        self.${w.name}.bind("<Key>", lambda e: self.on_${w.name}_key(e))`);
          break;
      }
    }
  }
  if (bindings.length === 0) {
    L.push('        pass');
  } else {
    L.push(...bindings);
  }

  // ── _expose_widgets: make widgets available as module-level globals ──
  L.push('');
  L.push('    def _expose_widgets(self):');
  L.push('        import sys');
  L.push('        m = sys.modules.get("__main__")');
  L.push('        if m:');
  L.push('            for k, v in vars(self).items():');
  L.push('                if not k.startswith("_") and k != "root":');
  L.push('                    setattr(m, k, v)');

  // ── on_start stub (overridden in main.py) ──
  L.push('');
  L.push('    def on_start(self):');
  L.push('        """Override this in main.py to run code at startup."""');
  L.push('        pass');

  // ── setup_pygame helper (only when a PygameCanvas widget exists) ──
  if (hasPygame) {
    L.push('');
    L.push('    def setup_pygame(self, frame, width, height):');
    L.push('        """Embed a pygame surface into a tkinter frame.');
    L.push('        Works on Windows and Linux. On macOS pygame opens its own window.');
    L.push('        Call this from on_start(), then call self._game_loop()."""');
    L.push('        import pygame');
    L.push('        if sys.platform in ("win32", "linux", "linux2"):');
    L.push('            frame.update()');
    L.push('            os.environ["SDL_WINDOWID"] = str(frame.winfo_id())');
    L.push('            if sys.platform.startswith("linux"):');
    L.push('                os.environ["SDL_VIDEODRIVER"] = "x11"');
    L.push('        pygame.init()');
    L.push('        return pygame.display.set_mode((width, height))');
  }

  // ── Event handler stubs (so base class doesn't crash if student forgets) ──
  for (const w of widgets) {
    const events = w.events || {};
    for (const [evt, enabled] of Object.entries(events)) {
      if (!enabled) continue;
      L.push('');
      if (evt === 'change' && w.type === 'Scale') {
        L.push(`    def on_${w.name}_change(self, value):`);
      } else if (evt === 'key') {
        L.push(`    def on_${w.name}_key(self, event):`);
      } else {
        L.push(`    def on_${w.name}_${evt}(self):`);
      }
      L.push('        pass');
    }
  }

  // ── run() helper ──
  L.push('');
  L.push('');
  L.push('def run(app_class):');
  L.push('    """Launch the app. Called from main.py."""');
  L.push('    root = tk.Tk()');
  L.push('    app_class(root)');
  L.push('    root.mainloop()');
  L.push('');

  return L.join('\n');
}

// ══════════════════════════════════════════════════════════
//  main.py — STUDENT CODE (minimal template)
// ══════════════════════════════════════════════════════════
export function generateMainPyTemplate(widgets, userBlocks = {}) {
  const L = [];
  const handlers = collectEnabledHandlers(widgets);
  const pygameWidgets = widgets.filter((w) => w.type === 'PygameCanvas');
  const hasPygame = pygameWidgets.length > 0;
  const firstPygame = hasPygame ? pygameWidgets[0] : null;

  L.push('from gui import AppGUI, run');
  if (hasPygame) {
    L.push('import pygame');
  }
  L.push('');
  L.push('');
  L.push('class App(AppGUI):');
  L.push('');
  L.push('    def on_start(self):');

  // on_start body — pygame gets richer starter hints
  const onStartBody = normalizeUserBlockLines(userBlocks['on_start'] || '');
  if (onStartBody.length > 0) {
    onStartBody.forEach((line) => L.push(`        ${line}`));
  } else if (hasPygame) {
    const cn = `self.${firstPygame.name}`;
    L.push(`        # Set up pygame inside the canvas widget (size must match widget dimensions)`);
    L.push(`        self.screen = self.setup_pygame(${cn}, ${firstPygame.width}, ${firstPygame.height})`);
    L.push(`        ${cn}.FPS = 60`);
    L.push(`        ${cn}.clock = pygame.time.Clock()`);
    L.push('');
    L.push('        # Static drawing here (backgrounds, images etc.)');
    L.push('');
    L.push('        self._game_loop()');
  } else {
    L.push('        # Runs automatically when the app starts. Use button1, label1 etc.');
    L.push('        pass');
  }

  if (handlers.length > 0) {
    L.push('');
    L.push('    # ── Event Handlers ─────────────────────────');
    for (const h of handlers) {
      L.push('');
      L.push(`    def ${h.method}(${h.args}):`);
      addUserBlockLines(L, h.method, userBlocks, `# Called on ${h.event} for ${h.widget.name}. Use ${h.widget.name} directly.`);
    }
  }

  // Pygame game loop method
  if (hasPygame) {
    L.push('');
    L.push('    def _game_loop(self):');
    const loopBody = normalizeUserBlockLines(userBlocks['_game_loop'] || '');
    if (loopBody.length > 0) {
      loopBody.forEach((line) => L.push(`        ${line}`));
    } else {
      const cn = `self.${firstPygame.name}`;
      L.push('        # Handle events');
      L.push('        for event in pygame.event.get():');
      L.push('            if event.type == pygame.KEYDOWN and event.key == pygame.K_SPACE:');
      L.push('                pass  # keyboard event');
      L.push('            if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:');
      L.push('                pass  # mouse click event');
      L.push('');
      L.push('        # Game logic here');
      L.push('');
      L.push('        # Draw your scene here');
      L.push('        self.screen.fill((30, 30, 40))  # background colour');
      L.push('        pygame.display.update()');
      L.push('');
      L.push('        # Limit FPS and schedule the next frame');
      L.push(`        ${cn}.clock.tick(${cn}.FPS)`);
      L.push('        self.root.after(0, self._game_loop)');
    }
  }

  L.push('');
  L.push('');
  L.push('run(App)');
  L.push('');

  return L.join('\n');
}

function collectUserBlocks(mainPyCode, fallbackCode = '') {
  const marked = extractMarkedUserBlocks(mainPyCode);
  if (Object.keys(marked).length > 0) return marked;

  const legacyMain = extractLegacyMethodBodies(mainPyCode);
  const legacyFallback = extractLegacyMethodBodies(fallbackCode);
  return { ...legacyFallback, ...legacyMain };
}

export function enforceMainPyTemplate(mainPyCode, widgets, fallbackCode = '') {
  const userBlocks = collectUserBlocks(mainPyCode, fallbackCode);
  return generateMainPyTemplate(widgets, userBlocks);
}
